import '../../../common/thinEngine-e576a091.js';
import '../../../common/node-87d9c658.js';
import '../../../common/math.color-fc6e801e.js';
import '../../../common/performanceConfigurator-115fd081.js';
import '../../../common/guid-495ff9c7.js';
import '../../../common/math.axis-e7db27a6.js';
import '../../../common/uniformBuffer-e700d3a6.js';
import '../../../common/light-a23926e9.js';
export { S as SpotLight } from '../../../common/spotLight-edd9cb8c.js';
import '../../../common/math.size-6398c1e8.js';
import '../../../common/baseTexture-827d5047.js';
import '../../../common/texture-6b1db4fe.js';
